# Generated by Django 5.1.2 on 2026-09-26 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('avitotask', '0035_avitoaccount_export_revision_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('backfill_before', models.DateTimeField(blank=True, null=True)),
                ('backfill_complete', models.BooleanField(default=False)),
                ('lease_until', models.DateTimeField(blank=True, null=True)),
                ('lease_token', models.CharField(blank=True, max_length=32)),
                ('last_error', models.TextField(blank=True)),
                ('avito_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calls_sync_state', to='avitotask.avitoaccount')),
            ],
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100)),
                ('occurred_at', models.DateTimeField()),
                ('buyer_phone', models.CharField(blank=True, max_length=64)),
                ('seller_phone', models.CharField(blank=True, max_length=64)),
                ('virtual_phone', models.CharField(blank=True, max_length=64)),
                ('talk_duration', models.PositiveIntegerField(default=0)),
                ('waiting_duration', models.PositiveIntegerField(default=0)),
                ('is_missed', models.BooleanField(default=None, null=True)),
                ('call_type', models.CharField(blank=True, choices=[('new', 'Новый'), ('repeat', 'Повторный')], max_length=10, null=True)),
                ('avito_item_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('avito_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='avitotask.avitoaccount')),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='avitotask.avitolisting')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='accounts.workspace')),
            ],
            options={
                'indexes': [models.Index(fields=['workspace', 'avito_account', '-occurred_at', '-id'], name='idx_calls_workspace_time')],
                'constraints': [models.UniqueConstraint(fields=('avito_account', 'external_id'), name='uniq_call_account_external_id')],
            },
        ),
    ]
