# Generated by Django 5.1.2 on 2026-09-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('avitotask', '0035_avitoaccount_export_revision_and_more'),
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='normalized_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='callsyncstate',
            name='classification_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['avito_account', 'normalized_phone', 'occurred_at', 'external_id'], name='idx_calls_account_phone_time'),
        ),
    ]
