# Generated by Django 5.1.2 on 2026-09-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0002_call_normalized_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='callsyncstate',
            name='phase',
            field=models.CharField(blank=True, choices=[('syncing', 'Синхронизация'), ('classifying', 'Классификация')], max_length=16, null=True),
        ),
    ]
