# Generated by Django 5.1.2 on 2026-09-28 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0003_callsyncstate_phase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='seller_phone',
        ),
        migrations.RemoveField(
            model_name='call',
            name='virtual_phone',
        ),
    ]
