# Generated by Django 5.1.2 on 2026-10-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0004_remove_call_seller_phone_remove_call_virtual_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='callsyncstate',
            name='has_invalid_calls',
            field=models.BooleanField(default=False),
        ),
    ]
