# Generated by Django 5.1.2 on 2026-10-04 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0005_callsyncstate_has_invalid_calls'),
    ]

    operations = [
        migrations.AddField(
            model_name='callsyncstate',
            name='access_retry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
