# Generated by Django 5.1.2 on 2026-10-04 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0006_callsyncstate_access_retry_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='report_html',
            field=models.TextField(blank=True, default=''),
        ),
    ]
