# Generated by Django 5.1.2 on 2026-10-04 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0007_call_report_html'),
    ]

    operations = [
        migrations.RenameField(
            model_name='call',
            old_name='report_html',
            new_name='report_text',
        ),
    ]
