# Generated by Django 5.1.2 on 2026-08-15 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Automation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_type', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('enabled', 'Enabled'), ('disabled', 'Disabled'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('execution_mode', models.CharField(choices=[('manual', 'Manual')], default='manual', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_automations', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_automations', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automations', to='accounts.workspace')),
            ],
            options={
                'indexes': [models.Index(fields=['workspace', 'state'], name='idx_auto_workspace_state')],
                'constraints': [models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='chk_auto_version_positive')],
            },
        ),
    ]
