# Generated by Django 5.1.2 on 2026-08-15 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('automations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_kind', models.CharField(choices=[('preview', 'Preview'), ('execute', 'Execute')], max_length=16)),
                ('trigger', models.CharField(choices=[('manual', 'Manual')], default='manual', max_length=16)),
                ('execution_mode_snapshot', models.CharField(choices=[('manual', 'Manual')], max_length=20)),
                ('automation_version', models.PositiveIntegerField()),
                ('automation_name_snapshot', models.CharField(max_length=255)),
                ('module_type_snapshot', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('waiting_for_data', 'Waiting for data'), ('evaluating', 'Evaluating'), ('waiting_approval', 'Waiting approval'), ('effect_pending', 'Effect pending'), ('completed', 'Completed'), ('partial', 'Partial'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=32)),
                ('idempotency_key', models.CharField(blank=True, max_length=128, null=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('data_wait_attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('wait_started_at', models.DateTimeField(blank=True, null=True)),
                ('run_token', models.UUIDField(blank=True, editable=False, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='automations.automation')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_automation_runs', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_runs', to='accounts.workspace')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'next_attempt_at', 'id'], name='idx_autorun_status_next_id'), models.Index(fields=['automation', 'created_at'], name='idx_autorun_automation_created')],
                'constraints': [models.CheckConstraint(condition=models.Q(('automation_version__gte', 1)), name='chk_autorun_version_positive'), models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False), models.Q(('idempotency_key', ''), _negated=True)), fields=('automation', 'run_kind', 'idempotency_key'), name='uniq_autorun_client_key'), models.UniqueConstraint(condition=models.Q(('status__in', ['queued', 'waiting_for_data', 'evaluating', 'waiting_approval', 'effect_pending'])), fields=('automation', 'run_kind'), name='uniq_autorun_open_kind')],
            },
        ),
    ]
