# Generated by Django 5.1.2 on 2026-08-15 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('automations', '0002_automationrun'),
        ('avitotask', '0031_add_published_end_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvitoListingAutomationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_tree', models.JSONField()),
                ('action_type', models.CharField(max_length=64)),
                ('action_config', models.JSONField(blank=True, default=dict)),
                ('max_actions_per_run', models.PositiveSmallIntegerField(default=10)),
                ('approval_ttl_minutes', models.PositiveSmallIntegerField(default=1440)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('automation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avito_listing_config', to='automations.automation')),
                ('avito_account', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='avito_listing_automation_configs', to='avitotask.avitoaccount')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avito_listing_automation_configs', to='accounts.workspace')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('max_actions_per_run__gte', 1), ('max_actions_per_run__lte', 100)), name='chk_avcfg_actions_range'), models.CheckConstraint(condition=models.Q(('approval_ttl_minutes__gte', 60), ('approval_ttl_minutes__lte', 10080)), name='chk_avcfg_ttl_range')],
            },
        ),
    ]
