# Generated by Django 5.1.2 on 2026-08-15 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('automations', '0003_avitolistingautomationconfig'),
        ('avitotask', '0031_add_published_end_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvitoListingRunResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of_date', models.DateField()),
                ('target_max_id_snapshot', models.PositiveBigIntegerField(default=0)),
                ('condition_snapshot', models.JSONField()),
                ('action_snapshot', models.JSONField()),
                ('examples_snapshot', models.JSONField(blank=True, default=list)),
                ('checked', models.PositiveIntegerField(default=0)),
                ('ineligible', models.PositiveIntegerField(default=0)),
                ('insufficient_coverage', models.PositiveIntegerField(default=0)),
                ('not_matched', models.PositiveIntegerField(default=0)),
                ('matched', models.PositiveIntegerField(default=0)),
                ('deferred_by_run_limit', models.PositiveIntegerField(default=0)),
                ('pending_approval', models.PositiveIntegerField(default=0)),
                ('completed_actions', models.PositiveIntegerField(default=0)),
                ('failed_actions', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('avito_account', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='automation_run_results', to='avitotask.avitoaccount')),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avito_listing_result', to='automations.automationrun')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avito_listing_run_results', to='accounts.workspace')),
            ],
            options={
                'indexes': [models.Index(fields=['avito_account', 'as_of_date'], name='idx_avres_account_asof')],
            },
        ),
    ]
