# Generated by Django 5.1.2 on 2026-08-15 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('automations', '0004_avitolistingrunresult'),
        ('avitotask', '0031_add_published_end_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvitoListingDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_id_snapshot', models.PositiveBigIntegerField()),
                ('listing_snapshot', models.JSONField()),
                ('status', models.CharField(choices=[('pending_approval', 'Pending approval'), ('applying', 'Applying'), ('effect_pending', 'Effect pending'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('stale', 'Stale'), ('superseded', 'Superseded'), ('failed', 'Failed')], default='pending_approval', max_length=32)),
                ('automation_version', models.PositiveIntegerField()),
                ('active_since_snapshot', models.DateTimeField()),
                ('condition_snapshot', models.JSONField()),
                ('metrics_snapshot', models.JSONField()),
                ('action_snapshot', models.JSONField()),
                ('expires_at', models.DateTimeField()),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('action_applied_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('terminal_at', models.DateTimeField(blank=True, null=True)),
                ('required_export_revision', models.PositiveBigIntegerField(blank=True, null=True)),
                ('effect_attempts', models.PositiveSmallIntegerField(default=0)),
                ('next_effect_retry_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_avito_listing_decisions', to=settings.AUTH_USER_MODEL)),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avito_listing_decisions', to='automations.automation')),
                ('avito_account', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='automation_decisions', to='avitotask.avitoaccount')),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_decisions', to='avitotask.avitolisting')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_avito_listing_decisions', to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avito_listing_decisions', to='automations.automationrun')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avito_listing_decisions', to='accounts.workspace')),
            ],
            options={
                'indexes': [models.Index(fields=['run', 'status'], name='idx_avdec_run_status'), models.Index(fields=['listing', 'status'], name='idx_avdec_listing_status'), models.Index(fields=['status', 'expires_at'], name='idx_avdec_status_expires'), models.Index(fields=['terminal_at', 'id'], name='idx_avdec_terminal_id')],
                'constraints': [models.CheckConstraint(condition=models.Q(('listing_id_snapshot__gte', 1)), name='chk_avdec_listing_id_positive'), models.CheckConstraint(condition=models.Q(('automation_version__gte', 1)), name='chk_avdec_version_positive'), models.CheckConstraint(condition=models.Q(('required_export_revision__isnull', True), ('required_export_revision__gte', 1), _connector='OR'), name='chk_avdec_export_rev_positive'), models.UniqueConstraint(fields=('run', 'listing_id_snapshot'), name='uniq_avdec_run_listing')],
            },
        ),
    ]
