# Generated by Django 5.1.2 on 2026-08-15 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('automations', '0005_avitolistingdecision'),
        ('avitotask', '0031_add_published_end_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvitoAutomationAccountState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('idle', 'Свободно'), ('running', 'Выполняется')], default='idle', max_length=16)),
                ('run_token', models.UUIDField(blank=True, editable=False, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('avito_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='automation_state', to='avitotask.avitoaccount')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avito_automation_account_states', to='accounts.workspace')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'lease_expires_at', 'id'], name='idx_avstate_status_lease')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('heartbeat_at__isnull', True), ('lease_expires_at__isnull', True), ('run_token__isnull', True), ('status', 'idle')), models.Q(('heartbeat_at__isnull', False), ('lease_expires_at__gt', models.F('heartbeat_at')), ('lease_expires_at__isnull', False), ('run_token__isnull', False), ('status', 'running')), _connector='OR'), name='chk_avstate_lease_consistent')],
            },
        ),
    ]
