# Generated by Django 5.1.2 on 2026-08-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('automations', '0006_avitoautomationaccountstate'),
        ('avitotask', '0034_remove_avitolisting_idx_avlisting_acc_mgmt'),
    ]

    operations = [
        migrations.AddField(
            model_name='avitolistingrunresult',
            name='max_actions_per_run_snapshot',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddConstraint(
            model_name='avitolistingrunresult',
            constraint=models.CheckConstraint(condition=models.Q(('max_actions_per_run_snapshot__gte', 1), ('max_actions_per_run_snapshot__lte', 100)), name='chk_avres_actions_range'),
        ),
    ]
