# Generated by Django 5.1.2 on 2026-08-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('automations', '0007_avitolistingrunresult_max_actions_per_run_snapshot_and_more'),
        ('avitotask', '0034_remove_avitolisting_idx_avlisting_acc_mgmt'),
    ]

    operations = [
        migrations.AddField(
            model_name='avitolistingrunresult',
            name='approval_ttl_minutes_snapshot',
            field=models.PositiveSmallIntegerField(default=1440),
        ),
        migrations.AddConstraint(
            model_name='avitolistingrunresult',
            constraint=models.CheckConstraint(condition=models.Q(('approval_ttl_minutes_snapshot__gte', 60), ('approval_ttl_minutes_snapshot__lte', 10080)), name='chk_avres_ttl_range'),
        ),
    ]
