FROM node:20-alpine AS build

WORKDIR /usr/src/app

ENV NODE_OPTIONS=--max-old-space-size=2048

COPY package.json package-lock.json* ./
RUN npm ci

COPY . .
RUN npm run build


FROM nginx:1.27-alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /usr/src/app/dist /usr/share/nginx/html

EXPOSE 80