services: 
  redis:
    image: redis:7.0.11-alpine


  django:
    container_name: django
    build:
      context: ./system
    command: uvicorn system.asgi:application --host 0.0.0.0 --port 8000 --workers 4 --log-level debug --reload --reload-dir /usr/src/app/templates --reload-dir /usr/src/app/static
    volumes: 
      - ./system:/usr/src/app/
    ports:
      - 8001:8000
    environment:
      - DEBUG=1
      - SECRET_KEY=042847234525
      - ALLOW_HOSTS=localhost, 127.0.0.1
    depends_on:
      - redis
  celery:
    container_name: celery
    build:
      context: ./system
    command: celery --app=system worker -l INFO
    volumes: 
      - ./system:/usr/src/app/  
    environment:
      - DEBUG=1
      - SECRET_KEY=042847234525
      - ALLOW_HOSTS=localhost, 127.0.0.1
    depends_on:
      - redis  