# Generated by Django 5.1.2 on 2026-03-23 13:16

import avitotask.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='Название категории', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Категория объявлений',
                'verbose_name_plural': 'Категории объявлений',
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='Product1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, help_text='Заголовок продукта', max_length=255)),
                ('urls', models.JSONField(blank=True, default=list, help_text='Список URL фото продукта')),
                ('description', models.TextField(help_text='Описание продукта')),
                ('created_date', models.DateField(auto_now_add=True, help_text='Дата добавления записи')),
                ('task_id', models.IntegerField(blank=True, default=0, null=True)),
                ('selected_option', avitotask.models.MyJSONField(blank=True, default=dict, encoder=avitotask.models.MyJSONEncoder, null=True)),
                ('project_name', avitotask.models.MyJSONField(blank=True, default=list, encoder=avitotask.models.MyJSONEncoder, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('price', models.IntegerField(blank=True, default=0, null=True)),
                ('activate', models.BooleanField(default=True, help_text='Активна ли задача для выполнения', null=True)),
                ('price_min', models.IntegerField(blank=True, default=0, null=True)),
                ('price_max', models.IntegerField(blank=True, default=0, null=True)),
                ('price_step', models.IntegerField(blank=True, default=0, null=True)),
                ('possible_combinations', models.IntegerField(blank=True, default=0, null=True)),
                ('schedule', models.JSONField(blank=True, default=dict, help_text="Расписание обновлений в формате {'Monday': '13:00', 'Saturday': '14:00'}")),
                ('next_update_time', models.DateTimeField(blank=True, help_text='Точное время следующего обновления цены', null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('titles', models.JSONField(blank=True, default=list, help_text='Список заголовков для продукта')),
                ('main_images', models.JSONField(blank=True, default=list, help_text='Основные изображения задачи', null=True)),
                ('additional_images', models.JSONField(blank=True, default=list, help_text='Дополнительные изображения задачи', null=True)),
                ('descriptions', models.JSONField(blank=True, default=dict, help_text='Описание задачи', null=True)),
                ('addresses', models.JSONField(blank=True, default=list, help_text='Адреса продукта', null=True)),
                ('selected_options', models.JSONField(blank=True, default=dict, help_text='Сохраненные опции и значения')),
                ('listingfee', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('contactphone', models.CharField(blank=True, max_length=12, null=True)),
                ('managername', models.CharField(blank=True, max_length=20, null=True)),
                ('avitostatus', models.CharField(blank=True, max_length=10, null=True)),
                ('companyname', models.CharField(blank=True, max_length=50, null=True)),
                ('contactmethod', models.CharField(blank=True, max_length=50, null=True)),
                ('adtype', models.CharField(blank=True, max_length=30, null=True)),
                ('availability', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.ForeignKey(blank=True, help_text='Категория товара', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='avitotask.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=avitotask.models.product_image_upload_to)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='avitotask.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_title_ru', models.CharField(help_text='Название опции (например, Цвет, Размер)', max_length=255)),
                ('option_title_en', models.CharField(help_text='Параметр для автозагрузки', max_length=150)),
                ('categories', models.ManyToManyField(blank=True, help_text='Категории, в которых доступна эта опция', related_name='options', to='avitotask.category')),
            ],
            options={
                'verbose_name': 'Опция товара',
                'verbose_name_plural': 'Опции товаров',
                'ordering': ['option_title_ru'],
            },
        ),
        migrations.CreateModel(
            name='ProductOptionAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_value', models.CharField(help_text='Выбранное значение опции', max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avitotask.product')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avitotask.productoptions')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='options',
            field=models.ManyToManyField(blank=True, related_name='products', through='avitotask.ProductOptionAssignment', to='avitotask.productoptions'),
        ),
        migrations.AddField(
            model_name='product',
            name='projects',
            field=models.ManyToManyField(related_name='projects', to='avitotask.project'),
        ),
    ]
