# Generated by Django 5.1.2 on 2026-04-22 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avitotask', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoptions',
            name='allow_multiple_options',
            field=models.BooleanField(default=False, help_text='Можно ли указать несколько значений для этой опции'),
        ),
        migrations.AlterField(
            model_name='productoptionassignment',
            name='selected_value',
            field=models.JSONField(blank=True, default=list, help_text='Значения, введенные пользователем для этой опции'),
        ),
        migrations.AlterUniqueTogether(
            name='productoptionassignment',
            unique_together={('product', 'option')},
        ),
    ]
