# Generated by Django 5.1.2 on 2026-04-22 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avitotask', '0002_productoptions_allow_multiple_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_randomization_enabled',
            field=models.BooleanField(default=False, help_text='Включена ли рандомизация цены'),
        ),
    ]
