# Generated by Django 5.1.2 on 2026-05-03 14:12

import avitotask.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('avitotask', '0004_product_workspace_product1_workspace_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('auto', 'Автогенерация'), ('manual', 'Ручной масс-постинг'), ('import', 'Импорт из Avito')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('completed', 'Завершено'), ('failed', 'Ошибка')], default='draft', max_length=20)),
                ('total_creatives', models.PositiveIntegerField(default=0)),
                ('total_publications', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ad_batches', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_batches', to='accounts.workspace')),
            ],
            options={
                'verbose_name': 'Пакет объявлений',
                'verbose_name_plural': 'Пакеты объявлений',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdGenerationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('titles', avitotask.models.MyJSONField(blank=True, default=list, encoder=avitotask.models.MyJSONEncoder)),
                ('descriptions', avitotask.models.MyJSONField(blank=True, default=dict, encoder=avitotask.models.MyJSONEncoder)),
                ('main_images', avitotask.models.MyJSONField(blank=True, default=list, encoder=avitotask.models.MyJSONEncoder)),
                ('additional_images', avitotask.models.MyJSONField(blank=True, default=list, encoder=avitotask.models.MyJSONEncoder)),
                ('addresses', avitotask.models.MyJSONField(blank=True, default=list, encoder=avitotask.models.MyJSONEncoder)),
                ('base_data', avitotask.models.MyJSONField(blank=True, default=dict, encoder=avitotask.models.MyJSONEncoder, help_text='Общие поля объявления для CSV: цена, контакты, тип объявления и т.д.')),
                ('selected_options', avitotask.models.MyJSONField(blank=True, default=dict, encoder=avitotask.models.MyJSONEncoder, help_text='Выбранные параметры Avito для задачи генерации.')),
                ('price', models.IntegerField(blank=True, default=0, null=True)),
                ('price_min', models.IntegerField(blank=True, default=0, null=True)),
                ('price_max', models.IntegerField(blank=True, default=0, null=True)),
                ('price_step', models.IntegerField(blank=True, default=0, null=True)),
                ('price_randomization_enabled', models.BooleanField(default=False)),
                ('possible_combinations', models.IntegerField(blank=True, default=0, null=True)),
                ('schedule', avitotask.models.MyJSONField(blank=True, default=dict, encoder=avitotask.models.MyJSONEncoder, help_text="Расписание вида {'Пн': '12:00', 'Ср': '12:00'} или нормализованный аналог.")),
                ('publication_interval_days', models.PositiveSmallIntegerField(choices=[(7, 'Каждые 7 дней'), (14, 'Каждые 14 дней'), (21, 'Каждые 21 день'), (28, 'Каждые 28 дней')], default=7)),
                ('schedule_cycle_started_at', models.DateTimeField(blank=True, null=True)),
                ('next_update_time', models.DateTimeField(blank=True, null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_generation_tasks', to='avitotask.category')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_generation_tasks', to='accounts.workspace')),
            ],
            options={
                'verbose_name': 'Задача генерации объявлений',
                'verbose_name_plural': 'Задачи генерации объявлений',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdCreative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('auto', 'Автогенерация'), ('manual', 'Ручное создание'), ('import', 'Импорт из Avito')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image_urls', avitotask.models.MyJSONField(blank=True, default=list, encoder=avitotask.models.MyJSONEncoder)),
                ('base_data', avitotask.models.MyJSONField(blank=True, default=dict, encoder=avitotask.models.MyJSONEncoder, help_text='Общие CSV-поля этого варианта объявления.')),
                ('option_data', avitotask.models.MyJSONField(blank=True, default=dict, encoder=avitotask.models.MyJSONEncoder, help_text='Параметры Avito для этого варианта объявления.')),
                ('identity_hash', models.CharField(blank=True, help_text='Хэш набора title/description/images/options для быстрой проверки дублей.', max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creatives', to='avitotask.adbatch')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_creatives', to='accounts.workspace')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creatives', to='avitotask.adgenerationtask')),
            ],
            options={
                'verbose_name': 'Креатив объявления',
                'verbose_name_plural': 'Креативы объявлений',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='adbatch',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='avitotask.adgenerationtask'),
        ),
        migrations.CreateModel(
            name='AdGenerationTaskOptionAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_value', avitotask.models.MyJSONField(blank=True, default=list, encoder=avitotask.models.MyJSONEncoder)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avitotask.productoptions')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avitotask.adgenerationtask')),
            ],
            options={
                'verbose_name': 'Опция задачи генерации',
                'verbose_name_plural': 'Опции задач генерации',
            },
        ),
        migrations.AddField(
            model_name='adgenerationtask',
            name='options',
            field=models.ManyToManyField(blank=True, related_name='ad_generation_tasks', through='avitotask.AdGenerationTaskOptionAssignment', to='avitotask.productoptions'),
        ),
        migrations.CreateModel(
            name='AvitoAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('external_account_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avito_accounts', to='accounts.workspace')),
            ],
            options={
                'verbose_name': 'Аккаунт Авито',
                'verbose_name_plural': 'Аккаунты Авито',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AdPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('auto', 'Автогенерация'), ('manual', 'Ручной масс-постинг'), ('import', 'Импорт из Avito')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активно'), ('paused', 'Приостановлено'), ('archived', 'Архив'), ('error', 'Ошибка')], default='draft', max_length=20)),
                ('row_id', models.CharField(blank=True, help_text='Наш внутренний ID строки для CSV и последующего связывания с Avito.', max_length=100, null=True)),
                ('address', models.TextField()),
                ('address_data', avitotask.models.MyJSONField(blank=True, default=dict, encoder=avitotask.models.MyJSONEncoder)),
                ('overrides', avitotask.models.MyJSONField(blank=True, default=dict, encoder=avitotask.models.MyJSONEncoder, help_text='Индивидуальные изменения этой публикации поверх AdCreative.base_data.')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('last_exported_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='avitotask.adbatch')),
                ('creative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='avitotask.adcreative')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='avitotask.adgenerationtask')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_publications', to='accounts.workspace')),
                ('avito_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='avitotask.avitoaccount')),
            ],
            options={
                'verbose_name': 'Публикация объявления',
                'verbose_name_plural': 'Публикации объявлений',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='adgenerationtask',
            name='avito_accounts',
            field=models.ManyToManyField(blank=True, related_name='generation_tasks', to='avitotask.avitoaccount'),
        ),
        migrations.CreateModel(
            name='AvitoListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avito_id', models.CharField(max_length=100)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('imported_payload', avitotask.models.MyJSONField(blank=True, default=dict, encoder=avitotask.models.MyJSONEncoder)),
                ('publiched_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('avito_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avito_listings', to='avitotask.avitoaccount')),
                ('publication', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avito_listings', to='avitotask.adpublication')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avito_listings', to='accounts.workspace')),
            ],
            options={
                'verbose_name': 'Объявление Avito',
                'verbose_name_plural': 'Объявления Avito',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AvitoListingDailyStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('views', models.PositiveIntegerField(default=0)),
                ('contacts', models.PositiveIntegerField(default=0)),
                ('favorites', models.PositiveIntegerField(default=0)),
                ('calls', models.PositiveIntegerField(default=0)),
                ('messages', models.PositiveIntegerField(default=0)),
                ('raw_metrics', avitotask.models.MyJSONField(blank=True, default=dict, encoder=avitotask.models.MyJSONEncoder)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='avitotask.avitolisting')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avito_listing_daily_stats', to='accounts.workspace')),
            ],
            options={
                'verbose_name': 'Дневная статистика Авито',
                'verbose_name_plural': 'Дневная статистика Авито',
                'ordering': ['-date'],
            },
        ),
    ]
