# Generated by Django 5.1.2 on 2026-05-03 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('avitotask', '0005_adbatch_adgenerationtask_adcreative_adbatch_task_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AvitoListingDailyStatus',
            new_name='AvitoListingDailyStats',
        ),
        migrations.RenameField(
            model_name='avitolisting',
            old_name='publiched_at',
            new_name='published_at',
        ),
        migrations.AlterField(
            model_name='avitolisting',
            name='publication',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avito_listing', to='avitotask.adpublication'),
        ),
        migrations.AddIndex(
            model_name='adbatch',
            index=models.Index(fields=['workspace', '-created_at'], name='idx_adbatch_ws_created'),
        ),
        migrations.AddIndex(
            model_name='adbatch',
            index=models.Index(fields=['workspace', 'task'], name='idx_adbatch_ws_task'),
        ),
        migrations.AddIndex(
            model_name='adbatch',
            index=models.Index(fields=['workspace', 'status'], name='idx_adbatch_ws_status'),
        ),
        migrations.AddIndex(
            model_name='adcreative',
            index=models.Index(fields=['workspace', 'task', '-created_at'], name='idx_adcreative_ws_task'),
        ),
        migrations.AddIndex(
            model_name='adcreative',
            index=models.Index(fields=['workspace', 'batch'], name='idx_adcreative_ws_batch'),
        ),
        migrations.AddIndex(
            model_name='adcreative',
            index=models.Index(fields=['workspace', 'identity_hash'], name='idx_adcreative_ws_hash'),
        ),
        migrations.AddIndex(
            model_name='adgenerationtask',
            index=models.Index(fields=['workspace', 'is_active', 'next_update_time'], name='idx_adtask_ws_next'),
        ),
        migrations.AddIndex(
            model_name='adgenerationtask',
            index=models.Index(fields=['workspace', '-created_at'], name='idx_adtask_ws_created_at'),
        ),
        migrations.AddIndex(
            model_name='adpublication',
            index=models.Index(fields=['workspace', 'avito_account', 'status'], name='idx_adpub_ws_acc_status'),
        ),
        migrations.AddIndex(
            model_name='adpublication',
            index=models.Index(fields=['workspace', 'creative'], name='idx_adpub_ws_creative'),
        ),
        migrations.AddIndex(
            model_name='adpublication',
            index=models.Index(fields=['workspace', 'task', 'status'], name='idx_adpub_ws_task_status'),
        ),
        migrations.AddIndex(
            model_name='adpublication',
            index=models.Index(fields=['workspace', 'batch'], name='idx_adpub_ws_batch'),
        ),
        migrations.AddIndex(
            model_name='adpublication',
            index=models.Index(fields=['workspace', 'avito_account', 'row_id'], name='idx_adpub_ws_row'),
        ),
        migrations.AddIndex(
            model_name='adpublication',
            index=models.Index(fields=['workspace', 'avito_account', '-created_at'], name='idx_adpub_ws_created'),
        ),
        migrations.AddIndex(
            model_name='adpublication',
            index=models.Index(condition=models.Q(('status', 'active')), fields=['workspace', 'avito_account'], name='idx_adpub_active_export'),
        ),
        migrations.AddIndex(
            model_name='avitoaccount',
            index=models.Index(fields=['workspace', 'is_active'], name='idx_avacc_ws_active'),
        ),
        migrations.AddIndex(
            model_name='avitolisting',
            index=models.Index(fields=['workspace', 'avito_account', 'avito_id'], name='idx_avlisting_acc_id'),
        ),
        migrations.AddIndex(
            model_name='avitolisting',
            index=models.Index(fields=['publication'], name='idx_avlisting_pub'),
        ),
        migrations.AddIndex(
            model_name='avitolisting',
            index=models.Index(fields=['workspace', '-last_seen_at'], name='idx_avlisting_ws_seen'),
        ),
        migrations.AddIndex(
            model_name='avitolisting',
            index=models.Index(fields=['workspace', 'status'], name='idx_avlisting_ws_status'),
        ),
        migrations.AddIndex(
            model_name='avitolistingdailystats',
            index=models.Index(fields=['listing', 'date'], name='idx_avstats_listing_date'),
        ),
        migrations.AddIndex(
            model_name='avitolistingdailystats',
            index=models.Index(fields=['workspace', '-date'], name='idx_avstats_ws_date'),
        ),
        migrations.AddIndex(
            model_name='product1',
            index=models.Index(fields=['task_id', 'created_date'], name='idx_product1_task_date'),
        ),
        migrations.AddIndex(
            model_name='product1',
            index=models.Index(fields=['workspace', 'task_id', 'created_date'], name='idx_product1_ws_task_date'),
        ),
        migrations.AddConstraint(
            model_name='adcreative',
            constraint=models.UniqueConstraint(condition=models.Q(('identity_hash__isnull', False), models.Q(('identity_hash', ''), _negated=True)), fields=('workspace', 'task', 'identity_hash'), name='uniq_adcreative_hash'),
        ),
        migrations.AddConstraint(
            model_name='adgenerationtaskoptionassignment',
            constraint=models.UniqueConstraint(fields=('task', 'option'), name='uniq_adtask_option'),
        ),
        migrations.AddConstraint(
            model_name='adpublication',
            constraint=models.UniqueConstraint(condition=models.Q(('row_id__isnull', False), models.Q(('row_id', ''), _negated=True)), fields=('workspace', 'avito_account', 'row_id'), name='uniq_adpub_row'),
        ),
        migrations.AddConstraint(
            model_name='avitoaccount',
            constraint=models.UniqueConstraint(fields=('workspace', 'name'), name='uniq_avacc_ws_name'),
        ),
        migrations.AddConstraint(
            model_name='avitoaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('external_account_id__isnull', False), models.Q(('external_account_id', ''), _negated=True)), fields=('workspace', 'external_account_id'), name='uniq_avacc_ws_ext'),
        ),
        migrations.AddConstraint(
            model_name='avitolisting',
            constraint=models.UniqueConstraint(fields=('workspace', 'avito_account', 'avito_id'), name='uniq_avlisting_id'),
        ),
        migrations.AddConstraint(
            model_name='avitolistingdailystats',
            constraint=models.UniqueConstraint(fields=('listing', 'date'), name='uniq_avstats_listing_date'),
        ),
    ]
