# Generated by Django 5.1.2 on 2026-05-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('avitotask', '0006_rename_avitolistingdailystatus_avitolistingdailystats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avitoaccount',
            name='export_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avitoaccount',
            name='export_file_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='avitoaccount',
            name='export_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avitoaccount',
            name='export_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avitoaccount',
            name='export_status',
            field=models.CharField(choices=[('clean', 'CSV актуален'), ('dirty', 'CSV требует пересборки'), ('exporting', 'CSV пересобирается'), ('error', 'Ошибка пересборки CSV')], default='clean', max_length=20),
        ),
        migrations.AddField(
            model_name='avitoaccount',
            name='last_export_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='avitoaccount',
            index=models.Index(fields=['workspace', 'export_status'], name='idx_avacc_ws_export'),
        ),
    ]
