# Generated by Django 5.1.2 on 2026-05-04 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avitotask', '0007_avitoaccount_export_error_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avitoaccount',
            old_name='last_export_at',
            new_name='last_exported_at',
        ),
    ]
