# Generated by Django 5.1.2 on 2026-05-05 09:50

import avitotask.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('avitotask', '0008_rename_last_export_at_avitoaccount_last_exported_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvitoOAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_type', models.CharField(choices=[('authorization_code', 'Authorization Code'), ('client_credentials', 'Client Credentials')], default='authorization_code', max_length=32)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('token_type', models.CharField(default='Bearer', max_length=32)),
                ('scope', models.TextField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user_info', avitotask.models.MyJSONField(blank=True, default=dict, encoder=avitotask.models.MyJSONEncoder)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_refreshed_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('avito_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_tokens', to='avitotask.avitoaccount')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avito_oauth_tokens', to='accounts.workspace')),
            ],
            options={
                'verbose_name': 'OAuth-токен Avito',
                'verbose_name_plural': 'OAuth-токены Avito',
                'indexes': [models.Index(fields=['workspace', 'expires_at'], name='idx_avtoken_ws_exp'), models.Index(fields=['workspace', 'auth_type'], name='idx_avtoken_ws_auth')],
            },
        ),
    ]
