# Generated by Django 5.1.2 on 2026-05-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avitotask', '0009_avitooauthtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='avitoaccount',
            name='client_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='avitoaccount',
            name='client_secret',
            field=models.TextField(blank=True),
        ),
    ]
