# Generated by Django 5.1.2 on 2026-05-10 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('avitotask', '0010_avitoaccount_client_id_avitoaccount_client_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='avitoaccount',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avitoaccount',
            name='sync_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avitoaccount',
            name='sync_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avitoaccount',
            name='sync_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avitoaccount',
            name='sync_status',
            field=models.CharField(choices=[('idle', 'Нет активной синхронизации'), ('queued', 'Синхронизация в очереди'), ('syncing', 'Синхронизация выполняется'), ('error', 'Ошибка синхронизации')], default='idle', max_length=20),
        ),
        migrations.AddIndex(
            model_name='avitoaccount',
            index=models.Index(fields=['workspace', 'sync_status'], name='idx_avacc_ws_sync'),
        ),
    ]
