# Generated by Django 5.1.2 on 2026-05-12 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avitotask', '0011_avitoaccount_last_synced_at_avitoaccount_sync_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avitoaccount',
            name='last_sync_created_listings',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='avitoaccount',
            name='last_sync_created_publications',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='avitoaccount',
            name='last_sync_total_received',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='avitoaccount',
            name='last_sync_updated_listings',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
