# Generated by Django 5.1.2 on 2026-05-14 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avitotask', '0012_avitoaccount_last_sync_created_listings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adcreative',
            name='source',
            field=models.CharField(choices=[('auto', 'Автогенерация'), ('manual', 'Ручное создание')], max_length=20),
        ),
        migrations.AlterField(
            model_name='adpublication',
            name='source',
            field=models.CharField(choices=[('auto', 'Автогенерация'), ('manual', 'Ручной масс-постинг')], max_length=20),
        ),
    ]
