# Generated by Django 5.1.2 on 2026-05-15 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avitotask', '0013_alter_adcreative_source_alter_adpublication_source'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='adcreative',
            name='uniq_adcreative_hash',
        ),
        migrations.AddField(
            model_name='adcreative',
            name='dedupe_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='adcreative',
            name='dedupe_images_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='adcreative',
            name='dedupe_title',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
