# Generated by Django 5.1.2 on 2026-05-15 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avitotask', '0014_remove_adcreative_uniq_adcreative_hash_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avitoaccount',
            name='last_sync_created_publications',
        ),
    ]
