# Generated by Django 5.1.2 on 2026-05-15 13:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avitotask', '0015_remove_avitoaccount_last_sync_created_publications'),
    ]

    operations = [
        migrations.AddField(
            model_name='adgenerationtask',
            name='last_run_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adgenerationtask',
            name='last_run_status',
            field=models.CharField(choices=[('idle', 'Ожидает'), ('running', 'Выполняется'), ('success', 'Успешно'), ('error', 'Ошибка')], default='idle', max_length=20),
        ),
        migrations.AddField(
            model_name='adgenerationtask',
            name='last_successful_run_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adgenerationtask',
            name='schedule_anchor_date',
            field=models.DateField(default=django.utils.timezone.localdate, help_text='Дата-якорь для расчета недельных интервалов 1/2/3/4.'),
        ),
        migrations.AddField(
            model_name='adgenerationtask',
            name='schedule_timezone',
            field=models.CharField(default='Europe/Moscow', help_text='Timezone расписания задачи, например Europe/Moscow.', max_length=64),
        ),
    ]
