# Generated by Django 5.1.2 on 2026-05-15 14:47

import avitotask.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('avitotask', '0016_adgenerationtask_last_run_error_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdGenerationTaskRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_by', models.CharField(choices=[('manual', 'Ручной запуск'), ('schedule', 'Запуск по расписанию')], max_length=20)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Выполняется'), ('success', 'Успешно'), ('error', 'Ошибка')], default='running', max_length=20)),
                ('publications_count', models.PositiveIntegerField(default=0)),
                ('csv_export_ids', avitotask.models.MyJSONField(blank=True, default=list, encoder=avitotask.models.MyJSONEncoder)),
                ('error', models.TextField(blank=True, null=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_runs', to='avitotask.adbatch')),
                ('creative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_runs', to='avitotask.adcreative')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='avitotask.adgenerationtask')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_generation_task_runs', to='accounts.workspace')),
            ],
            options={
                'verbose_name': 'Запуск задачи генерации',
                'verbose_name_plural': 'Запуски задач генерации',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['workspace', '-started_at'], name='idx_adtaskrun_ws_started'), models.Index(fields=['task', '-started_at'], name='idx_adtaskrun_task_started'), models.Index(fields=['task', 'status'], name='idx_adtaskrun_task_status')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('scheduled_for__isnull', False)), fields=('task', 'scheduled_for'), name='uniq_adtaskrun_task_scheduled')],
            },
        ),
    ]
