# Generated by Django 5.1.2 on 2026-05-16 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avitotask', '0017_adgenerationtaskrun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avitoaccount',
            name='export_status',
            field=models.CharField(choices=[('clean', 'CSV актуален'), ('dirty', 'CSV требует пересборки'), ('queued', 'CSV в очереди'), ('exporting', 'CSV пересобирается'), ('error', 'Ошибка пересборки CSV')], default='clean', max_length=20),
        ),
    ]
