# Generated by Django 5.1.2 on 2026-05-16 09:37

import avitotask.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0001_initial'),
        ('avitotask', '0018_alter_avitoaccount_export_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='options',
        ),
        migrations.RemoveField(
            model_name='product',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='product',
            name='workspace',

        ),
        migrations.AlterUniqueTogether(
            name='productoptionassignment',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='productoptionassignment',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product1',
            name='workspace',
        ),

        migrations.RemoveField(
            model_name='productoptionassignment',
            name='option',
        ),
        migrations.RemoveField(
            model_name='project',
            name='workspace',
        ),
        migrations.RemoveField(
            model_name='adgenerationtask',
            name='additional_images',
        ),
        migrations.RemoveField(
            model_name='adgenerationtask',
            name='main_images',
        ),
        migrations.RemoveField(
            model_name='adgenerationtask',
            name='schedule_cycle_started_at',
        ),
        migrations.CreateModel(
            name='AdImageAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=avitotask.models.ad_image_asset_upload_to)),
                ('url', models.URLField(blank=True, max_length=1000)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('checksum', models.CharField(blank=True, db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                  related_name='uploaded_ad_image_assets',
                                                  to=settings.AUTH_USER_MODEL)),
                ('workspace',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_image_assets',
                                   to='accounts.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='adgenerationtask',
            name='additional_image_assets',
            field=models.ManyToManyField(blank=True, related_name='additional_image_generation_tasks',
                                         to='avitotask.adimageasset'),
        ),
        migrations.AddField(
            model_name='adgenerationtask',
            name='main_image_assets',
            field=models.ManyToManyField(blank=True, related_name='main_image_generation_tasks',
                                         to='avitotask.adimageasset'),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Product1',
        ),
        migrations.DeleteModel(
            name='ProductOptionAssignment',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.AddIndex(
            model_name='adimageasset',
            index=models.Index(fields=['workspace', '-created_at'], name='idx_adimg_ws_created'),
        ),
        migrations.AddIndex(
            model_name='adimageasset',
            index=models.Index(fields=['workspace', 'checksum'], name='idx_adimg_ws_checksum'),
        ),
    ]
