# Generated by Django 5.1.2 on 2026-05-18 10:18

import avitotask.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('avitotask', '0019_remove_product_category_remove_product_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='adbatch',
            name='source',
            field=models.CharField(choices=[('auto', 'Автогенерация'), ('manual', 'Ручной масс-постинг'), ('import', 'Импорт из Avito'), ('avito_excel', 'Импорт из XLSX Avito')], max_length=20),
        ),
        migrations.AlterField(
            model_name='adpublication',
            name='source',
            field=models.CharField(choices=[('auto', 'Автогенерация'), ('manual', 'Ручной масс-постинг'), ('avito_excel', 'Импорт из XLSX Avito')], max_length=20),
        ),
        migrations.CreateModel(
            name='AvitoExcelImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_file', models.FileField(upload_to='avito-excel-imports/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('previewed', 'Проверен'), ('processing', 'Обрабатывается'), ('completed', 'Завершен'), ('failed', 'Ошибка')], default='processing', max_length=20)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('created_creatives', models.PositiveIntegerField(default=0)),
                ('created_publications', models.PositiveIntegerField(default=0)),
                ('updated_publications', models.PositiveIntegerField(default=0)),
                ('created_listings', models.PositiveIntegerField(default=0)),
                ('updated_listings', models.PositiveIntegerField(default=0)),
                ('report', avitotask.models.MyJSONField(blank=True, default=dict, encoder=avitotask.models.MyJSONEncoder)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('avito_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excel_imports', to='avitotask.avitoaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avito_excel_imports', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avito_excel_imports', to='accounts.workspace')),
            ],
            options={
                'verbose_name': 'Импорт XLSX Avito',
                'verbose_name_plural': 'Импорты XLSX Avito',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workspace', 'avito_account', '-created_at'], name='idx_avxls_ws_acc_created'), models.Index(fields=['workspace', 'status'], name='idx_avxls_ws_status')],
            },
        ),
    ]
