# Generated by Django 5.1.2 on 2026-05-18 10:37

import avitotask.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('avitotask', '0020_alter_adbatch_source_alter_adpublication_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avitolisting',
            name='base_data',
            field=avitotask.models.MyJSONField(blank=True, default=dict, encoder=avitotask.models.MyJSONEncoder, help_text='Нормализованные базовые поля объявления по option_title_en.'),
        ),
        migrations.AddField(
            model_name='avitolisting',
            name='category_path',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='avitolisting',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='avitolisting',
            name='image_urls',
            field=avitotask.models.MyJSONField(blank=True, default=list, encoder=avitotask.models.MyJSONEncoder),
        ),
        migrations.AddField(
            model_name='avitolisting',
            name='management_status',
            field=models.CharField(choices=[('observed', 'Только наблюдаем'), ('managed', 'Управляется сервисом'), ('out_of_sync', 'Есть расхождения')], default='observed', max_length=20),
        ),
        migrations.AddField(
            model_name='avitolisting',
            name='option_data',
            field=avitotask.models.MyJSONField(blank=True, default=dict, encoder=avitotask.models.MyJSONEncoder, help_text='Нормализованные параметры Avito по option_title_en.'),
        ),
        migrations.AddField(
            model_name='avitolisting',
            name='raw_data',
            field=avitotask.models.MyJSONField(blank=True, default=dict, encoder=avitotask.models.MyJSONEncoder, help_text='Исходная строка XLSX с русскими названиями колонок.'),
        ),
        migrations.AddField(
            model_name='avitolisting',
            name='row_id',
            field=models.CharField(blank=True, help_text='Id строки автозагрузки из XLSX/CSV.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='avitolisting',
            name='sheet_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='avitolisting',
            name='source',
            field=models.CharField(choices=[('api', 'Импорт из Avito API'), ('avito_excel', 'Импорт из XLSX Avito'), ('service', 'Создано сервисом')], default='api', max_length=20),
        ),
        migrations.AddField(
            model_name='avitolisting',
            name='unmapped_data',
            field=avitotask.models.MyJSONField(blank=True, default=dict, encoder=avitotask.models.MyJSONEncoder, help_text='Колонки XLSX, для которых не найден ProductOptions.'),
        ),
        migrations.AddIndex(
            model_name='avitolisting',
            index=models.Index(fields=['workspace', 'avito_account', 'source'], name='idx_avlisting_acc_source'),
        ),
        migrations.AddIndex(
            model_name='avitolisting',
            index=models.Index(fields=['workspace', 'avito_account', 'management_status'], name='idx_avlisting_acc_mgmt'),
        ),
        migrations.AddIndex(
            model_name='avitolisting',
            index=models.Index(fields=['workspace', 'avito_account', 'row_id'], name='idx_avlisting_acc_row'),
        ),
    ]
