# Generated by Django 5.1.2 on 2026-05-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avitotask', '0021_avitolisting_base_data_avitolisting_category_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avitolisting',
            name='address',
            field=models.TextField(blank=True),
        ),
    ]
