# Generated by Django 5.1.2 on 2026-05-18 13:50

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avitotask', '0022_avitolisting_address'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='productoptions',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('option_title_en')), name='uniq_product_options_option_title_en_ci_trim'),
        ),
    ]
