# Generated by Django 5.1.2 on 2026-05-19 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('avitotask', '0023_productoptions_uniq_product_options_option_title_en_ci_trim'),
    ]

    operations = [
        migrations.AddField(
            model_name='avitolisting',
            name='desired_status',
            field=models.CharField(choices=[('publish', 'Публиковать'), ('pause', 'Приостановить'), ('archive', 'Архивировать')], default='publish', help_text='Желаемое состояние объявления в следующем файле автозагрузки.', max_length=20),
        ),
        migrations.AddIndex(
            model_name='avitolisting',
            index=models.Index(fields=['workspace', 'avito_account', 'desired_status'], name='idx_avlisting_acc_desired'),
        ),
    ]
