# Generated by Django 5.1.2 on 2026-05-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('avitotask', '0024_avitolisting_desired_status_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='avitolisting',
            index=models.Index(fields=['workspace', 'avito_account', '-last_seen_at', '-created_at'], name='idx_avlisting_acc_seen'),
        ),
    ]
