# Generated by Django 5.1.2 on 2026-05-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avitotask', '0025_avitolisting_idx_avlisting_acc_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='avitoaccount',
            name='feed_token',
            field=models.CharField(blank=True, help_text='Публичный токен для CSV-фида автозагрузки Avito.', max_length=64, null=True, unique=True),
        ),
    ]
