# Generated by Django 5.1.2 on 2026-06-07 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avitotask', '0026_avitoaccount_feed_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AvitoListingDailyStats',
        ),
    ]
