# Generated by Django 5.1.2 on 2026-07-17 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avitotask', '0027_delete_avitolistingdailystats'),
    ]

    operations = [
        migrations.AddField(
            model_name='adcreative',
            name='option_category',
            field=models.ForeignKey(blank=True, help_text='Конечная категория, по которой выбираются разрешённые опции', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_creatives', to='avitotask.category'),
        ),
        migrations.AddField(
            model_name='avitolisting',
            name='option_category',
            field=models.ForeignKey(blank=True, help_text='Категория для отбора опций. Для импортированного объявления первоначально не заполняется.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avito_listings', to='avitotask.category'),
        ),
    ]
