# Generated by Django 5.1.2 on 2026-08-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('avitotask', '0031_add_published_end_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='avitolisting',
            name='active_since',
            field=models.DateTimeField(blank=True, help_text='Начало текущего непрерывного активного периода объявления.', null=True),
        ),
    ]
