# Generated by Django 5.1.2 on 2026-08-15 16:33

from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('accounts', '0001_initial'),
        ('avitotask', '0032_remove_avitolisting_idx_avlisting_acc_mgmt_and_more'),
    ]

    operations = [
        AddIndexConcurrently(
            model_name='avitolisting',
            index=models.Index(fields=['workspace', 'avito_account', 'management_status', 'active_since', 'id'], name='idx_avlisting_acc_active'),
        ),
    ]
