# Generated by Django 5.1.2 on 2026-08-15 16:35

from django.contrib.postgres.operations import RemoveIndexConcurrently
from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('avitotask', '0033_remove_avitolisting_idx_avlisting_acc_mgmt_and_more'),
    ]

    operations = [
        RemoveIndexConcurrently(
            model_name='avitolisting',
            name='idx_avlisting_acc_mgmt',
        ),
    ]
