# Generated by Django 5.1.2 on 2026-08-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('avitotask', '0034_remove_avitolisting_idx_avlisting_acc_mgmt'),
    ]

    operations = [
        migrations.AddField(
            model_name='avitoaccount',
            name='export_revision',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='avitoaccount',
            name='exporting_revision',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avitoaccount',
            name='last_exported_revision',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='avitoaccount',
            constraint=models.CheckConstraint(condition=models.Q(('last_exported_revision__lte', models.F('export_revision'))), name='chk_avacc_exported_rev_lte'),
        ),
        migrations.AddConstraint(
            model_name='avitoaccount',
            constraint=models.CheckConstraint(condition=models.Q(('exporting_revision__isnull', True), models.Q(('exporting_revision__gte', models.F('last_exported_revision')), ('exporting_revision__lte', models.F('export_revision'))), _connector='OR'), name='chk_avacc_exporting_rev_range'),
        ),
    ]
