# Generated by Django 5.1.2 on 2024-11-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cworker', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_running',
            field=models.BooleanField(default=False),
        ),
    ]
