# Generated by Django 5.1.2 on 2024-11-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('update_interval', models.IntegerField(default=24, help_text='Интервал обновления цены в часах')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
