# Generated by Django 5.1.2 on 2024-11-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cworker', '0003_post_is_running'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='interval',
            field=models.IntegerField(default=10, help_text='Интервал выполнения в секундах'),
        ),
    ]
