# Generated by Django 5.1.2 on 2024-11-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cworker', '0004_post_interval'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Заголовок записи', max_length=200)),
                ('interval', models.PositiveIntegerField(help_text='Интервал в секундах между выполнениями задачи')),
            ],
        ),
    ]
