# Generated by Django 5.1.2 on 2026-06-07 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('avitotask', '0027_delete_avitolistingdailystats'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvitoListingDailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('views', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('favorites', models.PositiveIntegerField(default=0)),
                ('calls', models.PositiveIntegerField(default=0)),
                ('messages', models.PositiveIntegerField(default=0)),
                ('total_spend', models.DecimalField(blank=True, decimal_places=2, help_text='Расходы по объявлению за день в рублях.', max_digits=12, null=True)),
                ('raw_metrics', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_daily_stats', to='avitotask.avitolisting')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avito_listing_daily_stats', to='accounts.workspace')),
            ],
            options={
                'verbose_name': 'Дневная статистика Avito',
                'verbose_name_plural': 'Дневная статистика Avito',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['listing', 'date'], name='idx_an_avstats_listing_date'), models.Index(fields=['workspace', '-date'], name='idx_an_avstats_ws_date')],
                'constraints': [models.UniqueConstraint(fields=('listing', 'date'), name='uniq_an_avstats_listing_date')],
            },
        ),
    ]
