# Generated by Django 5.1.2 on 2026-06-07 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avitolistingdailystats',
            old_name='clicks',
            new_name='contacts',
        ),
    ]
