# Generated by Django 5.1.2 on 2026-07-23 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('analytics', '0003_avito_stats_sync_state'),
        ('avitotask', '0031_add_published_end_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvitoListingStatsCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverage_from', models.DateField(blank=True, null=True)),
                ('finalized_through', models.DateField(blank=True, null=True)),
                ('last_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('last_successful_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_stats_coverage', to='avitotask.avitolisting')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avito_listing_stats_coverages', to='accounts.workspace')),
            ],
            options={
                'verbose_name': 'Покрытие статистики объявления Avito',
                'verbose_name_plural': 'Покрытия статистики объявлений Avito',
                'indexes': [models.Index(fields=['workspace', 'finalized_through'], name='idx_an_avcov_ws_final')],
            },
        ),
    ]
