# Generated by Django 5.1.2 on 2026-07-30 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_avitolistingstatscoverage'),
    ]

    operations = [
        migrations.AddField(
            model_name='avitolistingstatscoverage',
            name='spending_coverage_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avitolistingstatscoverage',
            name='spending_finalized_through',
            field=models.DateField(blank=True, null=True),
        ),
    ]
