# Generated by Django 5.1.2 on 2026-07-30 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_avitolistingstatscoverage_spending_coverage_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avitostatssyncstate',
            name='heartbeat_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avitostatssyncstate',
            name='run_id',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
